AppConfiguration:
  jwtSettings:
    issuer: config-server
    audience: "*"
    signingKey: di38dj38r73k27fhk38ufe28342i3h0eu8234bfe2ifh8cd897vf23f2323vref54gy23
UserDatabaseSetting:
  ConnectionName: mongodb://localhost:27017
  DatabaseName: UserService
  CollectionName: Users
eureka:
  client:
    shouldRegisterWithEureka: true
    serviceUrl: http://localhost:8010/eureka
    ValidateCertificates: false
  instance:
    appName: UserService
    hostName: localhost
